[project]
name = "auth-test"
version = "0.1.0"
description = "Add a short description here"
authors = ["Zend <zendwang040302@outlook.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.12.5,<4"
pip = ">=24.2,<25"

[pypi-dependencies]
starlette = ">=0.38.2, <0.39"
jupyter = ">=1.1.1, <2"
