site_name: 微服务速成笔记
site_url: https://finger-bone.github.io/mirco-service-crashcourse
theme:
  name: material
  language: zh

nav:
- Home: index.md
- Spring Cloud 微服务技术:
  - 回到 Spring: notes/01.md
  - 回到 Java: notes/02.md
  - Consul 作为服务注册中心: notes/03.md
  - Consul 作为配置中心: notes/04.md
  - LoadBalancer: notes/05.md
  - Http Interface Client 与 OpenFeign: notes/06.md
  - Resilience4j 服务熔断和降级: notes/07.md
  - Resilience4j 限流: notes/08.md
  - Micrometer 监控: notes/09.md
  - Spring Gateway 网关: notes/10.md
  - Seata 分布式事务: notes/11.md
- Spring 进阶内容:
  - Reactor 框架: notes/12.md
  - Spring WebFlux: notes/13.md
  - Spring Security: notes/14.md
  - Spring Security OAuth2 认证以及 KeyCloak 用户服务: notes/15.md
- 其它微服务进阶内容:
  - Rabbit MQ 消息队列: notes/16.md
  - GraphQL: notes/17.md
  - gRPC: notes/18.md
- k8s 微服务技术:
  - 后端框架一览: notes/19.md
  - k8s 无状态服务基本部署: notes/20.md
  - helm 打包 istio 网关与 k8s 命令行工具: notes/21.md
  - k8s 无状态服务: notes/22.md
  - k8s 有状态服务: notes/23.md
  - 服务网格: notes/24.md
- 中间件补充:
  - Nacos 服务治理: notes/25.md
  - Sentinel: notes/26.md
  - kafka 高性能消息队列: notes/27.md
  - Redis: notes/28.md
  - OTel-LGTM: notes/29.md
  - Dubbo RPC: notes/30.md
  - Nginx: notes/31.md
  - Treafik: notes/32.md
  - Citus: notes/33.md

markdown_extensions:
- toc:
    permalink: true
- tables
- fenced_code
