spring:
  application:
    name: app
  config:
    import:
    - nacos:d.yml
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
server:
  port: 8083